### ISSUE TITLE
Move createAccount function in service

### ISSUE THREAD

**Issue by bcalou** [FRobaglia/Memory-Front#40]
Vous faîtes bien de structurer votre projet avec des services.
Les composants ne devraient que traîter la partie visuelle / intéraction.
En l'occurence,  il serait donc bien de mettre createAccount, dans RegisterForm.js, à l'intérieur d'un service ;)

En gros, pas d'appel API directement dans les composants !

**Comment by tanamanda13** [comment]
createAccount a été déplacée dans SessionService (qui a repris AuthService). En résumé, j'ai réuni les functions qui étaient dans AuthService + createAccount dans SessionService. 
Branch : refacto/#23-register-clean-code
